-- 
CREATE TABLE users (
	id BIGSERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	login TEXT NOT NULL UNIQUE,
	password TEXT NOT NULL,
	role TEXT NOT NULL DEFAULT 'CUSTOMER',
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
-- 
CREATE TABLE users_tokens (
	token TEXT NOT NULL UNIQUE,
	user_id INTEGER NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	expire TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP + INTERVAL '1 hour'
);
-- 
CREATE TABLE categories (id BIGSERIAL PRIMARY KEY, name TEXT NOT NULL);
-- 
CREATE TABLE fotos (id BIGSERIAL PRIMARY KEY, name TEXT NOT NULL);
-- 
CREATE TABLE products (
	id BIGSERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	category_id TEXT NOT NULL,
	fotos_id INTEGER [] NOT NULL DEFAULT '{}',
	qty INTEGER NOT NULL,
	price INTEGER NOT NULL,
	active BOOLEAN NOT NULL DEFAULT false,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);